# babel-try-catch
babel-plugin

自动为函数添加try-catch并进行异常上报
